- id: '1632581953894'
  alias: auto__ovms_ev_charger_stop
  description: ''
  trigger:
  - platform: template
    value_template: '{{    (states(''sensor.ovms_state_of_charge'')| float >=  states(''input_number.target_soc'')|
      float) }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.garage_ev
      state: 'on'
    - condition: state
      entity_id: input_boolean.enable_ev_charger
      state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.garage_ev
  - service: script.1632642264104
  - service: script.1632645551231
  mode: single
- id: '1632643029908'
  alias: auto_ovms_ev_last_charged_timestamp
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.ovms_charge_state
    from: '"charging"'
    to: '"stopped","done"'
  condition: []
  action:
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.stopped_charge_date_time
    data:
      datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
  mode: single
- id: '1635261581403'
  alias: auto_update_argo
  description: ''
  trigger:
  - platform: time
    at: 03:00:00
